syntax = "proto3";

option csharp_namespace = "Artemis.Service.Protos.Business.VisionScreen";

package Artemis.Service.Protos.Business.VisionScreen;
import "google/api/annotations.proto";
import "google/protobuf/wrappers.proto";
import "business/visionscreening/visionscreening.proto";
import "common.proto";

// 视力筛查核心业务服务
service VisionScreeningCoreService{

    // 教师绑定用户
	rpc BindTeacherUser(BindTeacherUserRequest) returns (AffectedResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/BindTeacherUser"
			body: "*"
		};
	}

	// 解绑教师用户
	rpc UnBindTeacherUser(UnBindTeacherUserRequest) returns (AffectedResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/UnBindTeacherUser"
			body: "*"
		};
	}

	// 机构添加用户
	rpc BindOrganizationUsers(BindOrganizationUsersRequest) returns (AffectedResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/BindOrganizationUsers"
			body: "*"
		};
	}

	// 机构移除用户
	rpc UnBindOrganizationUsers(UnBindOrganizationUsersRequest) returns (AffectedResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/UnBindOrganizationUsers"
			body: "*"
		};
	}

	// 创建(子)任务
	rpc CreateOrAcceptTask(CreateOrAcceptTaskRequest) returns (AffectedResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/CreateOrAcceptTask"
			body: "*"
		};
	}

	// 获取当前未毕业班级的列表
	rpc FetchSchoolNotGraduatedClass(FetchSchoolNotGraduatedClassRequest) returns (FetchSchoolNotGraduatedClassResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/FetchSchoolNotGraduatedClass"
			body: "*"
		};
	}

	// 获取当前任务的学校列表
	rpc FetchTaskSchool(FetchTaskSchoolRequest) returns (FetchTaskSchoolResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/FetchTaskSchool"
			body: "*"
		};
	}

	// 获取当前任务的班级列表
	rpc FetchTaskClass(FetchTaskClassRequest) returns (FetchTaskClassResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/FetchTaskClass"
			body: "*"
		};
	}

	// 获取当前任务的学校班级列表
	rpc FetchTaskSchoolClass(FetchTaskSchoolClassRequest) returns (FetchTaskSchoolClassResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/FetchTaskSchoolClass"
			body: "*"
		};
	}

	// 创建任务目标和筛查记录
	rpc AcceptTaskUnit(AcceptTaskUnitRequest) returns (AffectedResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/AcceptTaskUnit"
			body: "*"
		};
	}

	// 查询根任务
	rpc FetchRootTask(FetchRootTaskRequest) returns (FetchRootTaskResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/FetchRootTask"
			body: "*"
		};
	}

	// 查询任务下级节点
	rpc FetchTaskSubNode(FetchTaskSubNodeRequest) returns (FetchTaskSubNodeResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/FetchTaskSubNode"
			body: "*"
		};
	}

	// 查询任务单元目标
	rpc FetchTaskUnitTarget(FetchTaskUnitTargetRequest) returns (FetchTaskUnitTargetResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/FetchTaskUnitTarget"
			body: "*"
		};
	}

	// 任务状态变更
	rpc TaskStateChange(TaskStateChangeRequest) returns (AffectedResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/TaskStateChange"
			body: "*"
		};
	}

	// 添加验光仪数据
	rpc AddOptometerPacket(AddOptometerRequest) returns (AffectedResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/AddOptometer"
			body: "*"
		};
	}

	// 添加电子视力表数据
	rpc AddVisualChartPacket(AddVisualChartRequest) returns (AffectedResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/AddVisualChart"
			body: "*"
		};
	}

	// 获取大屏学生视力档案
	rpc GetLargeScreenRecord(GetLargeScreenRecordRequest) returns (GetLargeScreenRecordResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/GetLargeScreenRecord"
			body: "*"
		};
	}

	// 获取通知消息(多端通用)
	rpc FetchUserMessage(EmptyRequest) returns (FetchUserMessageResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/FetchUserMessage"
			body: "*"
		};
	}

	// 读取通知消息(多端通用)
	rpc ReadUserMessage(ReadUserMessageRequest) returns (ReadUserMessageResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/ReadUserMessage"
			body: "*"
		};
	}

	// 获取系统模块树
	rpc FetchSystemModuleTree(EmptyRequest) returns (FetchSystemModuleTreeResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/FetchSystemModuleTree"
			body: "*"
		};
	}

	// 获取系统模块树(经凭据过滤)
	rpc FetchClaimedSystemModuleTree(EmptyRequest) returns (FetchSystemModuleTreeResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/FetchClaimedSystemModuleTree"
			body: "*"
		};
	}

	// 搜索视力档案
    rpc SearchRecordInfo (SearchRecordInfoRequest) returns (SearchRecordInfoResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/SearchRecordInfo"
			body: "*"
		};
	}

	// 查询仪表盘数据
	rpc DashboardData (DashboardDataRequerst) returns (DashboardDataResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/DashboardData"
			body: "*"
		};
	}

	// 请求批量PDF导出示例
    rpc MultiplePdfExportExample (ExportRequest) returns (stream ExportResponse){
		option (google.api.http) = {
			post: "/api/BusinessService/VisionScreeningCore/MultiplePdfExportExample"
			body: "*"
		};
	}
}

// 教师绑定用户请求
message BindTeacherUserRequest{
	// 教师标识
	// @required
	// @guid
	string TeacherId = 1;
	// 用户标识
	// @required
	// @guid
	string UserId = 2;
}

// 教师用户解绑请求
message UnBindTeacherUserRequest{
	// 教师标识
	// @required
	// @guid
	string TeacherId = 1;
}

// 机构添加用户请求
message BindOrganizationUsersRequest{
	// 机构标识
	// @required
	// @guid
	string OrganizationId = 1;
	// 用户标识
	// @required
	// @guid
	repeated string UserIds = 2;
}

// 机构移除用户请求
message UnBindOrganizationUsersRequest{
	// 机构标识
	// @required
	// @guid
	string OrganizationId = 1;
	// 用户标识
	// @required
	// @guid
	repeated string UserIds = 2;
}

// 创建(子)任务请求
message CreateOrAcceptTaskRequest{
	// 上级任务标识
	// @guid
	google.protobuf.StringValue TaskId = 1;
	// 任务名称
	// @required
	// @minLength(128)
	string TaskName = 2;
	// 本次任务(接收)创建的组织机构标识
	// @required
	// @guid
	string OrganizationId = 3;
	// 任务开始时间
	// @required
	// @datetime
	string StartTime = 4;
	// 任务结束时间
	// @required
	// @DateTime
	string EndTime = 5;
	// 下级管理机构的组织机构标识
	// @required
	// @guid
	repeated string SubManagementOrganizationIds = 6;
	// 下级职能机构的组织机构标识
	// @required
	// @guid
	repeated string SubFunctionalOrganizationIds = 7;
}

// 获取当前未毕业班级的列表请求
message FetchSchoolNotGraduatedClassRequest{
	// 学校标识
	// @required
	// @guid
	string SchoolId = 1;
}

// 当前未毕业班级数据包
message SchoolNotGraduatedClassPacket{
	// 学校标识
	// @required
	// @guid
	string SchoolId = 1;
	// 班级标识
	// @required
	// @guid
	string ClassId = 2;
	// 班级名称
	google.protobuf.StringValue ClassName = 3;
	// 班级人数
	int32 Count = 4;
}

// 获取当前未毕业班级的列表响应
message FetchSchoolNotGraduatedClassResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 当前未毕业班级信息
	// @required
	repeated SchoolNotGraduatedClassPacket Data = 7;
}

// 获取当前任务的学校列表请求
message FetchTaskSchoolRequest{
	// 任务标识
	// @required
	// @guid
	string TaskId = 1;
}

// 当前任务的学校数据包
message TaskSchoolPacket{
	// 任务标识
	// @required
	// @guid
	string TaskId = 1;
	// 学校标识
	// @required
	// @guid
	string SchoolId = 2;
	// 班级名称
	google.protobuf.StringValue SchoolName = 3;
	// 班级人数
	int32 Count = 4;
}

// 获取当前任务的学校列表响应
message FetchTaskSchoolResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 当前任务的学校数据
	// @required
	repeated TaskSchoolPacket Data = 7;
}

// 获取当前任务的班级列表请求
message FetchTaskClassRequest{
	// 任务标识
	// @required
	// @guid
	string TaskId = 1;
}

// 当前任务的班级数据包
message TaskClassPacket{
	// 任务标识
	// @required
	// @guid
	string TaskId = 1;
	// 班级标识
	// @required
	// @guid
	string ClassId = 2;
	// 学校名称
	google.protobuf.StringValue SchoolName = 3;
	// 班级名称
	google.protobuf.StringValue ClassName = 4;
	// 班级人数
	int32 Count = 5;
}

// 获取当前任务的班级列表响应
message FetchTaskClassResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 当前任务的学校数据
	// @required
	repeated TaskClassPacket Data = 7;
}

// 获取当前任务的特定学校的班级列表请求
message FetchTaskSchoolClassRequest{
	// 任务标识
	// @required
	// @guid
	string TaskId = 1;
	// 学校标识
	// @required
	// @guid
	string SchoolId = 2;
}

// 当前任务的特定学校的班级数据包
message TaskSchoolClassPacket{
	// 任务标识
	// @required
	// @guid
	string TaskId = 1;
	// 学校标识
	// @required
	// @guid
	string SchoolId = 2;
	// 学校名称
	google.protobuf.StringValue SchoolName = 3;
	// 班级标识
	// @required
	// @guid
	string ClassId = 4;
	// 班级名称
	google.protobuf.StringValue ClassName = 5;
	// 班级人数
	int32 Count = 6;
}

// 获取当前任务的特定学校的班级列表响应
message FetchTaskSchoolClassResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 当前任务的特定学校的班级数据
	// @required
	repeated TaskSchoolClassPacket Data = 7;
}

// 创建任务目标和筛查记录请求
message AcceptTaskUnitRequest{
	// 任务单元标识
	// @required
	// @guid
	string TaskUnitId = 1;
	// 学校标识
	// @required
	// @guid
	string SchoolId = 2;
	// 班级标识
	// @required
	// @guid
	repeated string ClassIds = 3;
}

// 查询根任务请求
message FetchRootTaskRequest{
	// 任务名称搜索值
	google.protobuf.StringValue TaskNameSearch = 1;
	// 任务计划开始时间
	// @datetime
	google.protobuf.StringValue StartTime =2;
	// 任务计划结束时间
	// @datetime
	google.protobuf.StringValue EndTime =3;
	// 任务状态
	google.protobuf.StringValue TaskState = 4;
	// 页码
	// @min(0)
	google.protobuf.Int32Value Page = 5;
	// 条目数
	// @min(0)
	google.protobuf.Int32Value Size = 6;
}

// 根任务信息
message TaskPacket{
	// 任务标识
	// @required
	// @guid
	string Id = 1;
	// 父任务标识
	// @guid
	google.protobuf.StringValue ParentId = 2;
	// 任务名称
	google.protobuf.StringValue TaskName = 3;
	// 任务编码
	// @required
	string TaskCode = 4;
	// 关联机构编码
	// @required
	string DesignCode = 5;
	// 任务归属
	// @required
	string TaskShip = 6;
	// 任务状态
	// @required
	string TaskState = 7;
	// 任务描述
	google.protobuf.StringValue Description = 8;
	// 计划开始时间
	// @datetime
	google.protobuf.StringValue StartTime = 9;
	// 计划结束时间
	// @datetime
	google.protobuf.StringValue EndTime = 10;
}

// 分页根任务信息数据包
message PagedRootTaskPacket{
	// 页码
	// @min(0)
	int32 Page = 1;
	// 条目数
	// @min(0)
	int32 Size = 2;
	// 数据总数
	// @min(0)
	int64 Total = 3;
	// 条件过滤后的数据量
	// @min(0)
	int64 Count = 4;
	// 角色用户信息数据
	// @required
	repeated TaskPacket Items = 5;
}

// 查询根任务响应
message FetchRootTaskResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 分页根任务信息
	// @required
	PagedRootTaskPacket Data = 7;
}

// 查询下级任务请求
message FetchTaskSubNodeRequest{
	// 任务标识
	// @required
	// @guid
	string Id = 1;
}

// 任务单元数据包
message TaskUnitPacket{
	// 任务单元标识
	// @required
	// @guid
	string Id = 1;
	// 任务标识
	// @required
	// @guid
	string TaskId = 2;
	// 任务单元名称
	google.protobuf.StringValue UnitName = 3;
	// 任务单元编码
	// @required
	string UnitCode = 4;
	// 关联机构编码
	// @required
	string DesignCode = 5;
	// 任务单元状态
	// @required
	string TaskUnitState = 7;
	// 任务单元描述
	google.protobuf.StringValue Description = 8;
}

// 下级任务数据包
message TaskSubNodePacket{
	// 子任务
	repeated TaskPacket Children = 1;
	// 任务单元
	repeated TaskUnitPacket TaskUnits = 2;
}

// 查询下级任务响应
message FetchTaskSubNodeResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 任务树信息
	// @required
	TaskSubNodePacket Data = 7;
}

// 查询任务单元目标请求
message FetchTaskUnitTargetRequest{
	// 任务单元
	// @required
	// @guid
	string Id = 1;
}

// 任务目标数据包
message TaskUnitTargetInfoPacket{
	// 任务单元目标标识
	// @required
	// @guid
	string Id = 1;
	// 任务单元标识
	// @required
	// @guid
	string TaskUnitId = 2;
	// 任务单元名称
	google.protobuf.StringValue TargetName = 3;
	// 任务单元编号
	google.protobuf.StringValue TargetCode = 4;
	// 关联学生标识
	google.protobuf.StringValue BindingTag = 5;
	// 目标状态
	// @required
	string TargetState = 6;
	// 任务目标描述
	google.protobuf.StringValue Description = 7;
	// 任务目标执行时间
	google.protobuf.StringValue ExecuteTime = 8;
}

// 查询任务单元目标响应
message FetchTaskUnitTargetResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 任务目标数据
	// @required
	repeated TaskUnitTargetInfoPacket Data = 7;
}


// 任务状态变更请求
message TaskStateChangeRequest{
	// 任务标识
	// @guid
	google.protobuf.StringValue TaskId = 1;
	// 任务标识
	// @guid
	google.protobuf.StringValue TaskUnitId = 2;
	// 任务标识
	// @guid
	google.protobuf.StringValue TaskUnitTargetId = 3;
	// 需要修改到的目标状态
	google.protobuf.StringValue State = 4;
}

// 验光仪数据包
message OptometerPacket{
	// 瞳距
	google.protobuf.DoubleValue PupilDistance = 1;
	// 左眼球镜
	google.protobuf.DoubleValue LeftSphere = 2;
	// 左眼等效球镜
	google.protobuf.DoubleValue LeftEquivalentSphere = 3;
	// 右眼球镜
	google.protobuf.DoubleValue RightSphere = 4;
	// 右眼等效球镜
	google.protobuf.DoubleValue RightEquivalentSphere = 5;
	// 左眼柱镜
	google.protobuf.DoubleValue LeftCylinder = 6;
	// 右眼柱镜
	google.protobuf.DoubleValue RightCylinder = 7;
	// 左眼轴位
	google.protobuf.DoubleValue LeftAxis = 8;
	// 右眼轴位
	google.protobuf.DoubleValue RightAxis = 9;
	// 左眼散光度数
	google.protobuf.DoubleValue LeftAstigmatism = 10;
	// 右眼散光度数
	google.protobuf.DoubleValue RightAstigmatism = 11;
	// 左眼角膜曲率r1(mm)
	google.protobuf.DoubleValue LeftCornealCurvatureR1 = 12;
	// 右眼角膜曲率r1(mm)
	google.protobuf.DoubleValue RightCornealCurvatureR1 = 13;
	// 左眼角膜曲率r1(d)
	google.protobuf.DoubleValue LeftCornealCurvatureD1 = 14;
	// 右眼角膜曲率r1(d)
	google.protobuf.DoubleValue RightCornealCurvatureD1 = 15;
	// 左眼角膜曲率r1角度
	google.protobuf.DoubleValue LeftCornealCurvatureAngle1 = 16;
	// 右眼角膜曲率r1角度
	google.protobuf.DoubleValue RightCornealCurvatureAngle1 = 17;
	// 左眼角膜曲率r2(mm)
	google.protobuf.DoubleValue LeftCornealCurvatureR2 = 18;
	// 右眼角膜曲率r2(mm)
	google.protobuf.DoubleValue RightCornealCurvatureR2 = 19;
	// 左眼角膜曲率r2(d)
	google.protobuf.DoubleValue LeftCornealCurvatureD2 = 20;
	// 右眼角膜曲率r2(d)
	google.protobuf.DoubleValue RightCornealCurvatureD2 = 21;
	// 左眼角膜曲率r2角度
	google.protobuf.DoubleValue LeftCornealCurvatureAngle2 = 22;
	// 右眼角膜曲率r2角度
	google.protobuf.DoubleValue RightCornealCurvatureAngle2 = 23;
	// 左眼角膜曲率平均值(mm)
	google.protobuf.DoubleValue LeftCornealCurvatureAverage = 24;
	// 右眼角膜曲率平均值(mm)
	google.protobuf.DoubleValue RightCornealCurvatureAverage = 25;
	// 左眼角膜曲率平均值(d)
	google.protobuf.DoubleValue LeftCornealCurvatureAverageD = 26;
	// 右眼角膜曲率平均值(d)
	google.protobuf.DoubleValue RightCornealCurvatureAverageD = 27;
	// 左眼角膜曲率散光度
	google.protobuf.DoubleValue LeftCornealCurvatureAstigmatism = 28;
	// 右眼角膜曲率散光度
	google.protobuf.DoubleValue RightCornealCurvatureAstigmatism = 29;
	// 筛查工作人员姓名
	google.protobuf.StringValue OptometerScreeningStuffName = 30;
	// 操作时间
	google.protobuf.StringValue OptometerOperationTime = 31;
	// 左眼瞳孔半径
	google.protobuf.DoubleValue LeftPupilRadius = 32;
	// 右眼瞳孔半径
	google.protobuf.DoubleValue RightPupilRadius = 33;
	// 左眼垂直方向斜视度数
	google.protobuf.DoubleValue LeftVerticalAxis = 34;
	// 右眼垂直方向斜视度数
	google.protobuf.DoubleValue RightVerticalAxis = 35;
	// 左眼水平方向斜视度数
	google.protobuf.DoubleValue LeftHorizontalAxis = 36;
	// 右眼水平方向斜视度数
	google.protobuf.DoubleValue RightHorizontalAxis = 37;
	// 左眼红光反射
	google.protobuf.StringValue LeftRedReflect = 38;
	// 右眼红光反射
	google.protobuf.StringValue RightRedReflect = 39;
}

// 添加验光仪数据请求
message AddOptometerRequest{
	// 记录标识
	// @required
	// @guid
	string RecordId = 1;
	// 验光仪数据包
	// @required
	OptometerPacket OptometerPacket = 2;
}

// 电子视力表数据包
message VisualChartPacket{
	// 左眼与视力表距离
	google.protobuf.DoubleValue LeftChartDistance = 1;
	// 右眼与视力表距离
	google.protobuf.DoubleValue RightChartDistance = 2;
	// 左眼裸眼视力
	google.protobuf.DoubleValue LeftNakedEyeVision = 3;
	// 右眼裸眼视力
	google.protobuf.DoubleValue RightNakedEyeVision = 4;
	// 是否佩戴眼镜
	bool IsWearGlasses = 5;
	// 左眼矫正视力
	google.protobuf.DoubleValue LeftCorrectedVision = 6;
	// 右眼矫正视力
	google.protobuf.DoubleValue RightCorrectedVision = 7;
	// 左眼远视力类型
	google.protobuf.StringValue LeftEyeHyperopiaType = 8;
	// 右眼远视力类型
	google.protobuf.StringValue RightEyeHyperopiaType = 9;
	// 左眼是否佩戴角膜塑形镜
	google.protobuf.BoolValue IsWareLeftOkLenses = 10;
	// 右眼是否佩戴角膜塑形镜
	google.protobuf.BoolValue IsWareRightOkLenses = 11;
	// 筛查工作人员姓名
	google.protobuf.StringValue ChartScreeningStuffName = 12;
	// 操作时间
	google.protobuf.StringValue ChartOperationTime = 13;
}

// 添加电子视力表数据请求
message AddVisualChartRequest{
	// 记录标识
	// @required
	// @guid
	string RecordId = 1;
	// 电子视力表数据包
	// @required
	VisualChartPacket VisualChartPacket = 2;
}

// 获取大屏学生视力档案请求
message GetLargeScreenRecordRequest{
	// 任务标识
	// @required
	// @guid
	string TaskId = 1;
	// 学生标识
	// @required
	// @guid
	string StudentId = 2;
}

// 大屏学生视力档案数据包
message LargeScreenRecordPacket {
	// 档案标识
	// @required
	// @guid
	string Id = 1;
	// 学生标识
	// @required
	// @guid
	string StudentId = 2;
	// 学生姓名
	google.protobuf.StringValue StudentName = 3;
	// 学生性别
	google.protobuf.StringValue Gender = 4;
	// 学生年龄
	google.protobuf.Int32Value Age = 5;
	// 学生班级
	google.protobuf.StringValue ClassName = 6;
	// 学生学校
	google.protobuf.StringValue SchoolName = 7;
	// 学生民族
	google.protobuf.StringValue Nation = 8;
	//学生年级
	google.protobuf.StringValue GradeName = 9;
	// 学生生日
	// @datetime
	google.protobuf.StringValue Birthday = 10;
	// 左眼球镜
	google.protobuf.DoubleValue LeftSphere = 11;
	// 右眼球镜
	google.protobuf.DoubleValue RightSphere = 12;
	// 左眼柱镜
	google.protobuf.DoubleValue LeftCylinder = 13;
	// 右眼柱镜
	google.protobuf.DoubleValue RightCylinder = 14;
	// 左眼等效球镜
	google.protobuf.DoubleValue LeftEquivalentSphere = 15;
	// 右眼等效球镜
	google.protobuf.DoubleValue RightEquivalentSphere = 16;
	// 左眼散光度数
	google.protobuf.DoubleValue LeftAstigmatism = 17;
	// 右眼散光度数
	google.protobuf.DoubleValue RightAstigmatism = 18;
	// 左眼裸眼视力
	google.protobuf.DoubleValue LeftNakedEyeVision = 19;
	// 右眼裸眼视力
	google.protobuf.DoubleValue RightNakedEyeVision = 20;
	// 左眼矫正视力
	google.protobuf.DoubleValue LeftCorrectedVision = 21;
	// 右眼矫正视力
	google.protobuf.DoubleValue RightCorrectedVision = 22;
	// 瞳距
	google.protobuf.DoubleValue PupilDistance = 23;
	// 检查时间
	// @datetime
	google.protobuf.StringValue CheckTime = 24;
	// 家长关系
	google.protobuf.StringValue ParentRelation = 25;
	// 联系地址
	google.protobuf.StringValue Address = 26;
	// 家长手机号
	google.protobuf.StringValue ParentMobile = 27;
	// 医生建议
	google.protobuf.StringValue DoctorAdvice = 28;
}

// 获取大屏学生视力档案响应
message GetLargeScreenRecordResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 大屏学生视力档案数据包
	// @required
	LargeScreenRecordPacket Data = 7;
}

// 获取通知消息数据包
message FetchUserMessagePacket{
	// 未读数量
	int32 NotReadCount = 1;
	// 消息列表
	repeated NotificationMessagePacket Messages = 2;

}

// 获取用户通知消息(多端通用)
message FetchUserMessageResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 通知消息数据
	// @required
	FetchUserMessagePacket Data = 7;
}

// 读取通知消息请求
message ReadUserMessageRequest{
	// 消息标识
	string MessageId = 1;
}

// 读取通知消息响应
message ReadUserMessageResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 通知消息数据
	// @required
	NotificationMessagePacket Data = 7;
}

// 系统模块信息树数据包
message SystemModuleTreePacket{
	// 模块标识
	// @required
	// @guid
	string Id = 1;
	// 上级模块标识
	// @guid
	google.protobuf.StringValue ParentId = 2;
	// 模块名称
	// @required
	// @maxLength(128)
	string Name = 3;
	// 模块类型
	// @required
	string Type = 4;
	// 模块序列
	// @required
	// @min(0)
	int32 Order = 5;
	// 路由地址
	// @maxLength(128)
	google.protobuf.StringValue Path = 6;
	// 路由参数
	// @maxLength(256)
	google.protobuf.StringValue Parameters = 7;
	// 组件路径
	// @maxLength(128)
	google.protobuf.StringValue Component = 8;
	// 模块图标
	// @maxLength(64)
	google.protobuf.StringValue Icon = 9;
	// 是否外链
	// @required
	bool IsFrame = 10;
	// 是否显示
	// @required
	bool Visible = 11;
	// 模块状态
	// @required
	bool Status = 12;
	// 凭据戳
	// @maxLength(64)
	google.protobuf.StringValue ClaimStamp = 13;
	// 备注
	// @maxLength(256)
	google.protobuf.StringValue Remark = 14;
	// 子模块
	repeated SystemModuleTreePacket Children = 15;
}

// 读取系统模块信息树响应
message FetchSystemModuleTreeResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 系统模块信息数据
	// @required
	repeated SystemModuleTreePacket Data = 7;
}

// 批量导出PDF示例请求
message ExportRequest{
	// 导出数量
	int32 ExportCount = 1;
}

// 批量导出PDF示例数据包
message ExportPacket{
	// 总数
	int32 Total = 1;
	// 当前数
	int32 Count = 2;
	// 是否结束
	bool Completet = 3;
	// 下载地址
	google.protobuf.StringValue Url = 4;
}

// 批量导出PDF示例响应
message ExportResponse{
	// 状态码
	int32 Code = 1;
	// 是否成功
	bool Succeeded = 2;
	// 消息
	string Message = 3;
	// 错误
	// @exception
	google.protobuf.StringValue Error = 4;
	// 响应时间
	// @datetime
	string DateTime = 5;
	// 响应时间戳
	// @timestamp
	int64 Timestamp = 6;
	// 批量导出PDF示例数据
	// @required
	ExportPacket Data = 7;
}

// 搜索视力档案请求
message SearchRecordInfoRequest{
	// 任务标识
    // @guid
    google.protobuf.StringValue TaskId = 1;
    // 学生名称搜索值
    // @maxLength(128)
    google.protobuf.StringValue StudentName = 2;
	// 学校标识
    // @guid
    google.protobuf.StringValue SchoolId = 3;
	// 班级标识
    // @guid
    google.protobuf.StringValue classId = 4;
    // 页码
    // @min(0)
    google.protobuf.Int32Value Page = 5;
    // 条目数
    // @min(0)
    google.protobuf.Int32Value Size = 6;
}

// 视力档案信息数据包
message RecordInfoPacket{
	// 记录标识
	// @guid
	string Id = 1;
	// 生日
	google.protobuf.StringValue Birthday = 2;
	// 性别
	google.protobuf.StringValue Gender = 3;
	// 行政区划编码
	google.protobuf.StringValue DivisionCode = 4;
	// 所属地区(地级行政区划名)
	google.protobuf.StringValue PrefectureName = 5;
	// 所属县市(县级行政区划名)
	google.protobuf.StringValue CountyName = 6;
	// 任务名称
	google.protobuf.StringValue TaskName = 7;
	// 学校名称
	google.protobuf.StringValue SchoolName = 8;
	// 年级名称
	google.protobuf.StringValue GradeName = 9;
	// 班级名称
	google.protobuf.StringValue ClassName = 10;
	// 建档时间
	google.protobuf.StringValue CreatedAt = 11;
	// 筛查时间
	google.protobuf.StringValue CheckTime = 12;
	// 瞳距
	google.protobuf.StringValue PupilDistance = 13;
	// 左眼球镜
	google.protobuf.DoubleValue LeftSphere = 14;
	// 右眼球镜
	google.protobuf.DoubleValue RightSphere = 15;
	// 左眼柱镜
	google.protobuf.DoubleValue LeftCylinder = 16;
	// 右眼柱镜
	google.protobuf.DoubleValue RightCylinder = 17;
	// 左眼等效球镜
	google.protobuf.DoubleValue LeftEquivalentSphere = 18;
	// 右眼等效球镜
	google.protobuf.DoubleValue RightEquivalentSphere = 19;
	// 左眼散光度数
	google.protobuf.DoubleValue LeftAstigmatism = 20;
	// 右眼散光度数
	google.protobuf.DoubleValue RightAstigmatism = 21;
	// 左眼裸眼视力
	google.protobuf.DoubleValue LeftNakedEyeVision = 22;
	// 右眼裸眼视力
	google.protobuf.DoubleValue RightNakedEyeVision = 23;
	// 左眼矫正视力
	google.protobuf.DoubleValue LeftCorrectedVision = 24;
	// 右眼矫正视力
	google.protobuf.DoubleValue RightCorrectedVision = 25;
	// 左眼是否佩戴角膜塑形镜
	google.protobuf.BoolValue IsWareLeftOkLenses = 26;
	// 右眼是否佩戴角膜塑形镜
	google.protobuf.BoolValue IsWareRightOkLenses = 27;
	// 左眼轴位
	google.protobuf.DoubleValue LeftAxis = 28;
	// 右眼轴位
	google.protobuf.DoubleValue RightAxis = 29;
	// 左眼瞳孔半径
	google.protobuf.DoubleValue LeftPupilRadius = 30;
	// 右眼瞳孔半径
	google.protobuf.DoubleValue RightPupilRadius = 31;
	// 左眼垂直方向斜视度数
	google.protobuf.DoubleValue LeftVerticalAxis = 32;
	// 右眼垂直方向斜视度数
	google.protobuf.DoubleValue RightVerticalAxis = 33;
	// 左眼水平方向斜视度数
	google.protobuf.DoubleValue LeftHorizontalAxis = 34;
	// 右眼水平方向斜视度数
	google.protobuf.DoubleValue RightHorizontalAxis = 35;
	// 左眼红光反射
	google.protobuf.StringValue LeftRedReflect = 36;
	// 右眼红光反射
	google.protobuf.StringValue RightRedReflect = 37;
	// 筛查单位
	google.protobuf.StringValue TaskAgentName = 38;
	// 筛查工作人员姓名
	google.protobuf.StringValue OptometerScreeningStuffName = 39;
	// 医嘱
	google.protobuf.StringValue DoctorAdvice = 40;
	// 医师
	google.protobuf.StringValue DoctorName = 41;
	// 医嘱时间
	google.protobuf.StringValue PrescribedTime = 42;
	// 绑定微信号
	google.protobuf.StringValue WxNumber = 43;
	// 报告发送人
	google.protobuf.StringValue ReportSender = 44;
	// 报告发送时间
	google.protobuf.StringValue ReportSendTime = 45;
	// 报告签收人
	google.protobuf.StringValue ReportReceiver = 46;
	// 报告签收时间
	google.protobuf.StringValue ReportReceiveTime = 47;
	// 左眼图片
	google.protobuf.StringValue LeftEyePhoto = 48;
	// 右眼图片
	google.protobuf.StringValue RightEyePhoto = 49;
	// 双眼图片
	google.protobuf.StringValue BothEyePhoto = 50;
}

// 分页视力档案信息数据包
message PagedRecordInfoPacket {
    // 页码
    // @min(0)
    int32 Page = 1;
    // 条目数
    // @min(0)
    int32 Size = 2;
    // 数据总数
    // @min(0)
    int64 Total = 3;
    // 条件过滤后的数据量
    // @min(0)
    int64 Count = 4;
    // 视力档案信息数据包
    // @required
    repeated RecordInfoPacket Items = 5;
}

// 查询凭据信息响应
message SearchRecordInfoResponse {
    // 状态码
    int32 Code = 1;
    // 是否成功
    bool Succeeded = 2;
    // 响应消息
    string Message = 3;
    // 错误
    // @exception
    google.protobuf.StringValue Error = 4;
    // 响应时间
    // @datetime
    string DateTime = 5;
    // 响应时间戳
    // @timestamp
    int64 Timestamp = 6;
    // 分页视力档案信息数据包
    // @required
    PagedRecordInfoPacket Data = 7;
}

// 仪表盘数据请求
message DashboardDataRequerst{
	// 任务标识
	// @required
	// @guid
	string TaskId = 1;
	// 学校标识
	// @guid
	google.protobuf.StringValue SchoolId = 2;
	// 年级名称
	google.protobuf.StringValue GradeName = 3;
	// 标准标识
	google.protobuf.StringValue StandardId = 4;
}

// 仪表盘人数分布
message DashboardPopulationDistributionPacket{
	// 总人数
	int32 Total = 1;
	// 已筛查人数
	int32 Checked = 2;
	// 仅验光仪
	int32 OnlyOptoimeterChecked = 3;
	// 仅视力表
	int32 OnlyChartChecked = 4;
	// 未筛查人数
	int32 NotChecked = 5;
}

// 仪表盘新增统计
message DashboardIncreasedStatisticsPacket{
	// 新增数量
	int32 IncreasedCount = 1;
	// 同比增长率
	double YearOnYearIncreased = 2;
	// 环比增长率
	double TimeOnTimeIncreased = 3;
}

// 仪表盘标准分布项目数据包
message DashboardStandardDistributionItemPacket{
	// 项目名称
	string ItemName = 1;
	// 项目数量
	int32 ItemCount = 2;
	// 项目占比
	double ItemRate = 3;
}

// 仪表盘标准分布数据包
message DashboardStandardDistributionPacket{
	// 标准分布数据项目列表
	repeated DashboardStandardDistributionItemPacket Items = 1;
}

// 未筛查原因分布项目数据包
message DashBoardExceptionReasonItemPacket{
	// 项目名称
	string ItemName = 1;
	// 项目数量
	int32 ItemCount = 2;
}

// 未筛查原因分布数据包
message DashBoardExceptionReasonDistributionPacket{
	// 标准分布数据项目列表
	repeated DashBoardExceptionReasonItemPacket Items = 1;
}

// 年级班级分布项目数据包
message DashboardGradeOrClassDistributionItemPacket{
	// 项目名称
	string ItemName = 1;
	// 项目总数
	int32 ItemTotal = 2;
	// 项目数量
	int32 ItemCount = 3;
}

// 年级班级分布数据包
message DashboardGradeOrClassDistributionPacket{
	// 年级班级分布列表
	repeated DashboardGradeOrClassDistributionItemPacket Items = 1;
}

// 仪表盘数据包
message DashboardDataPacket{
	// 仪表盘人数分布
	DashboardPopulationDistributionPacket PopulationDistribution = 1;
	// 仪表盘新增统计
	DashboardIncreasedStatisticsPacket IncreasedStatistic = 2;
	// 仪表盘标准分布
	DashboardStandardDistributionPacket StandardDistribution = 3;
	// 仪表盘未筛查原因分布
	DashBoardExceptionReasonDistributionPacket ExceptionReasonDistribution = 4;
	// 年级班级数据分布
	DashboardGradeOrClassDistributionPacket GradeOrClassDistribution = 5;
}

// 查询仪表盘人数分布响应
message DashboardDataResponse {
    // 状态码
    int32 Code = 1;
    // 是否成功
    bool Succeeded = 2;
    // 响应消息
    string Message = 3;
    // 错误
    // @exception
    google.protobuf.StringValue Error = 4;
    // 响应时间
    // @datetime
    string DateTime = 5;
    // 响应时间戳
    // @timestamp
    int64 Timestamp = 6;
    // 仪表盘数据包
    // @required
    DashboardDataPacket Data = 7;
}