# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: push to nuget

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push:
    name: build, pack & push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Setup
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # Install
    - name: Install workload
      run: dotnet workload restore Artemis.sln
    # Restore
    - name: Restore dependencies
      run: dotnet restore Artemis.sln
    # Build
    - name: Build
      run: dotnet build Artemis.sln --configuration Release --no-restore
    # Pack
    - name: Pack
      run: dotnet pack ArtemisPackages.slnf --no-build --no-restore --configuration Release --output dist
# Publish
    - name: Push To GitHub Packages
      run: dotnet nuget push dist/*.nupkg --source https://nuget.pkg.github.com/zyltntking/index.json --api-key ${{secrets.GITHUB_PACKAGE_ARTEMIS}} --skip-duplicate